# Name used to track your version, no spaces!
root = "/home/rob/"
name = "noixtest3"
# If this is used to "provision" a reproducible kernel + files -> true
# Otherwise false
bootable = false
# if chroot should be immutable or not
immutable = false

# only if bootable is true
# kernel_version=6.6.0
# kernel_params=
# kernel_modules=["i915"]

# bind mounts (not copied over)
# by default /etc/noix/ is mounted to enable changing to different stores
# Also by fefault bind mounts are rw unless you add :ro at the end
# Mounting certain directories can mess up your system, beware!
bind_mounts = [
 "/proc",
]

sym_links = [
    ["/lib","usr/lib"],
    ["/bin","usr/bin"],
]

# sync paths (copied into the store)
sync_paths = [
 "/usr/bin/bash",
 "/usr/lib/x86_64-linux-gnu/libtinfo.so.6",
 "/lib/x86_64-linux-gnu/libc.so.6",
 "/lib/x86_64-linux-gnu/libselinux.so.1",
 "/lib/x86_64-linux-gnu/libcap.so.2",
 "/lib/x86_64-linux-gnu/libpcre2-8.so.0",
 "/lib/x86_64-linux-gnu/libselinux.so.1",
 "/lib64",
]

# Just creates the given dir path
# essentially runs mkdir -p
create_dirs = [
 "/tmp",
 ""
]


